### PR TITLE
fix(datasource-mongoose): mongoose 7.0 should return the right type for _id

### PR DESCRIPTION
**Pull request by Scra3**
linked to: CU-860q3wqaf

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

### CODE REVIEW

**Comment by Scra3** [comment]
The mongoose PR that introduce the change: https://github.com/Automattic/mongoose/commit/021862316ee2cd9ac7b1c8d5d6b0ba67745e0416

**Review by romain-gilliotte — CHANGES_REQUESTED** [review]
Can you add comments to the code to explain ObjectID vs ObjectId?

**Review by romain-gilliotte — CHANGES_REQUESTED** [review]
Also, you forgot to update package.json

**Comment by Scra3** [comment]
@romain-gilliotte I have moved the ObjectId in a constant to centralise the documentation and to remove the duplication

**Review by romain-gilliotte — APPROVED** [review]

**Pull request merged**
